import { useState } from 'react';
import Papa from 'papaparse';
import { SearchData } from '../utils/types';

/**
 * PapaParse auto-generates field names for malformed columns: "_1", "_2", etc.
 * for empty/blank headers (e.g. trailing commas in CSV), and "__parsed_extra"
 * when a row has more fields than the header count. This helper identifies
 * those so we can exclude them from the UI.
 */
function isAutoGeneratedColumn(name: string): boolean {
  return /^_\d+$/.test(name.trim()) || name.trim() === '' || name === '__parsed_extra';
}

export function useFileUpload() {
  const [parsedData, setParsedData] = useState<any[]>([]);
  const [availableColumns, setAvailableColumns] = useState<string[]>([]);
  const [selectedIdColumn, setSelectedIdColumn] = useState<string>('');
  const [selectedFileName, setSelectedFileName] = useState<string>('');
  const [searches, setSearches] = useState<SearchData[]>([]);
  const [uploadCounter, setUploadCounter] = useState<number>(0);
  // True when the current file was loaded via Load Layout (a saved layout), rather than
  // uploaded as a plain sample CSV. Lets the UI label the loaded file as a layout.
  const [isLayoutFile, setIsLayoutFile] = useState<boolean>(false);

  // Trim the ID value and drop rows whose ID is blank or whitespace-only, matching the ID-column
  // validation in App.tsx (idColumnIssues). Keeps loaded searches consistent with the warnings and
  // with the trimmed values used for name-based lookups on export/save.
  const processSearchData = (data: any[], idColumn: string): SearchData[] => {
    return data
      .filter((row: any) => String(row[idColumn] ?? '').trim() !== '')
      .map((row: any) => ({
        name: String(row[idColumn]).trim(),
        metadata: Object.keys(row)
          .filter((key) => key !== idColumn && !isAutoGeneratedColumn(key))
          .reduce((acc, key) => ({ ...acc, [key.trim()]: row[key] }), {}),
      }));
  };

  /**
   * Parse sample-CSV text and load it as the current data set. Synchronous: Papa parses the
   * in-memory text directly (the caller has already read the file), so the outcome can be
   * returned rather than delivered through a callback. Returns `ok: false` with an error when
   * the file has no readable columns, and an optional warning when rows had formatting problems.
   */
  const loadSampleCsvText = (
    text: string,
    fileName: string
  ): { ok: boolean; error?: string; warning?: string } => {
    const results = Papa.parse<Record<string, string>>(text, {
      header: true,
      skipEmptyLines: 'greedy',
    });
    const fields = results.meta.fields || [];
    const headers = fields.filter(h => !isAutoGeneratedColumn(h));

    if (headers.length === 0) {
      // No usable columns - not a readable CSV.
      resetFileState();
      return {
        ok: false,
        error: `Could not read any columns from "${fileName}". Please choose a valid .csv file with a header row.`,
      };
    }

    // Require a real tabular structure: the first row must be a header whose cells are all
    // non-blank. Tolerate a single trailing blank, which is just a stray trailing comma.
    // Anything else, for example an injection-sequence export that starts with a
    // "Bracket Type=4,,,," directive, is not a sample list.
    const blankHeaderCells = fields.filter(isAutoGeneratedColumn);
    const onlyTrailingBlankHeader =
      blankHeaderCells.length === 0 ||
      (blankHeaderCells.length === 1 && isAutoGeneratedColumn(fields[fields.length - 1]));
    if (!onlyTrailingBlankHeader) {
      resetFileState();
      return {
        ok: false,
        error: `The first row of "${fileName}" has empty column headings, so it does not look like a sample list. Please choose a .csv where the first row contains column headers.`,
      };
    }

    // No row may carry a value beyond the named header columns. This covers:
    //  - a row with more cells than the header, whose surplus Papa collects in __parsed_extra, and
    //  - a value under a tolerated trailing blank column, which must stay empty in every row.
    // An old CSV layout file, whose data rows are wider than its two-column header, is rejected here.
    const hasCellBeyondHeaders = (row: any): boolean => {
      const overflow = row.__parsed_extra;
      if (Array.isArray(overflow) && overflow.some((v: any) => String(v ?? '').trim() !== '')) {
        return true;
      }
      return blankHeaderCells.some(key => String(row[key] ?? '').trim() !== '');
    };
    if (results.data.some(hasCellBeyondHeaders)) {
      resetFileState();
      return {
        ok: false,
        error: `"${fileName}" has rows with more values than there are column headers, so it does not look like a simple table. Please choose a .csv where every row lines up with the header columns.`,
      };
    }

    setUploadCounter(c => c + 1);
    setSelectedFileName(fileName);
    setIsLayoutFile(false);
    setAvailableColumns(headers);
    setParsedData(results.data);

    // Auto-select reference column (prefer known ID column names)
    let defaultColumn = headers[0];
    const sampleIdMatch = headers.find(
      h => h.replace(/[_\s-]/g, '').toLowerCase() === 'sampleid'
    );
    if (headers.includes('search name')) {
      defaultColumn = 'search name';
    } else if (headers.includes('UW_Sample_ID')) {
      defaultColumn = 'UW_Sample_ID';
    } else if (sampleIdMatch) {
      defaultColumn = sampleIdMatch;
    }
    setSelectedIdColumn(defaultColumn);
    setSearches(processSearchData(results.data, defaultColumn));

    // Warn, without blocking the load, about content that may not have loaded correctly:
    //  - a row missing one or more named columns (fewer values than the header), and
    //  - a serious parse problem such as an unbalanced quote, which can silently swallow rows.
    // A row that only omits a tolerated trailing blank is not partial, so a clean trailing comma
    // does not warn. Field-count mismatches are ignored here because rows wider than the header
    // are already rejected above, and an undetectable delimiter is expected for a single column.
    const partialRows = results.data.filter(row => headers.some(h => !(h in row))).length;
    const hasParseProblem = results.errors.some(
      e => e.type !== 'FieldMismatch' && e.type !== 'Delimiter'
    );
    let warning: string | undefined;
    if (partialRows > 0) {
      warning = `"${fileName}" had ${partialRows} row(s) with fewer values than the header. ` +
        'Some values may not have loaded correctly.';
    } else if (hasParseProblem) {
      warning = `"${fileName}" had formatting problems while being read. ` +
        'Some values may not have loaded correctly.';
    }
    return { ok: true, warning };
  };

  /**
   * Load samples from a saved layout file. Unlike loadSampleCsvText, this sets the searches,
   * file name, columns, and ID column directly from the file's recorded settings, without
   * applying the auto-ID-column defaults. Bumps uploadCounter so the Sequence Export Wizard
   * remounts. The caller (App.applyLoadedLayout) restores the remaining settings.
   */
  const loadSearches = (
    loadedSearches: SearchData[],
    fileName: string,
    idColumn: string,
    metadataColumns: string[]
  ) => {
    setUploadCounter(c => c + 1);
    setSelectedFileName(fileName);
    setIsLayoutFile(true);
    setAvailableColumns([idColumn, ...metadataColumns]);
    setSelectedIdColumn(idColumn);
    setSearches(loadedSearches);
    // Imported layouts cannot be re-derived by changing the ID column, so clear parsedData.
    setParsedData([]);
  };

  /** Clear all file-derived state, returning the app to its pre-upload state. */
  const resetFileState = () => {
    setParsedData([]);
    setAvailableColumns([]);
    setSelectedIdColumn('');
    setSelectedFileName('');
    setSearches([]);
    setIsLayoutFile(false);
  };

  const handleIdColumnChange = (event: React.ChangeEvent<HTMLSelectElement>) => {
    const newIdColumn = event.target.value;
    setSelectedIdColumn(newIdColumn);

    if (parsedData.length > 0) {
      const processedSearches = processSearchData(parsedData, newIdColumn);
      setSearches(processedSearches);
    }
  };

  return {
    searches,
    parsedData,
    availableColumns,
    selectedIdColumn,
    selectedFileName,
    isLayoutFile,
    uploadCounter,
    loadSampleCsvText,
    handleIdColumnChange,
    loadSearches,
    resetFileState,
  };
}