import { useState } from 'react';
import Papa from 'papaparse';
import { SearchData } from '../utils/types';

/**
 * PapaParse auto-generates field names for malformed columns: "_1", "_2", etc.
 * for empty/blank headers (e.g. trailing commas in CSV), and "__parsed_extra"
 * when a row has more fields than the header count. This helper identifies
 * those so we can exclude them from the UI.
 */
function isAutoGeneratedColumn(name: string): boolean {
  return /^_\d+$/.test(name.trim()) || name.trim() === '' || name === '__parsed_extra';
}

export function useFileUpload() {
  const [parsedData, setParsedData] = useState<any[]>([]);
  const [availableColumns, setAvailableColumns] = useState<string[]>([]);
  const [selectedIdColumn, setSelectedIdColumn] = useState<string>('');
  const [selectedFileName, setSelectedFileName] = useState<string>('');
  const [searches, setSearches] = useState<SearchData[]>([]);
  const [uploadCounter, setUploadCounter] = useState<number>(0);
  // True when the current file was loaded via Load Layout (a saved layout), rather than
  // uploaded as a plain sample CSV. Lets the UI label the loaded file as a layout.
  const [isLayoutFile, setIsLayoutFile] = useState<boolean>(false);

  // Trim the ID value and drop rows whose ID is blank or whitespace-only, matching the ID-column
  // validation in App.tsx (idColumnIssues). Keeps loaded searches consistent with the warnings and
  // with the trimmed values used for name-based lookups on export/save.
  const processSearchData = (data: any[], idColumn: string): SearchData[] => {
    return data
      .filter((row: any) => String(row[idColumn] ?? '').trim() !== '')
      .map((row: any) => ({
        name: String(row[idColumn]).trim(),
        metadata: Object.keys(row)
          .filter((key) => key !== idColumn && !isAutoGeneratedColumn(key))
          .reduce((acc, key) => ({ ...acc, [key.trim()]: row[key] }), {}),
      }));
  };

  /**
   * Parse sample-CSV text and load it as the current data set. Synchronous: Papa parses the
   * in-memory text directly (the caller has already read the file), so the outcome can be
   * returned rather than delivered through a callback. Returns `ok: false` with an error when
   * the file has no readable columns, and an optional warning when rows had formatting problems.
   */
  const loadSampleCsvText = (
    text: string,
    fileName: string
  ): { ok: boolean; error?: string; warning?: string } => {
    const results = Papa.parse<Record<string, string>>(text, {
      header: true,
      skipEmptyLines: 'greedy',
    });
    const headers = (results.meta.fields || []).filter(h => !isAutoGeneratedColumn(h));

    if (headers.length === 0) {
      // No usable columns - not a readable CSV.
      resetFileState();
      return {
        ok: false,
        error: `Could not read any columns from "${fileName}". Please choose a valid .csv file with a header row.`,
      };
    }

    setUploadCounter(c => c + 1);
    setSelectedFileName(fileName);
    setIsLayoutFile(false);
    setAvailableColumns(headers);
    setParsedData(results.data);

    // Auto-select reference column (prefer known ID column names)
    let defaultColumn = headers[0];
    const sampleIdMatch = headers.find(
      h => h.replace(/[_\s-]/g, '').toLowerCase() === 'sampleid'
    );
    if (headers.includes('search name')) {
      defaultColumn = 'search name';
    } else if (headers.includes('UW_Sample_ID')) {
      defaultColumn = 'UW_Sample_ID';
    } else if (sampleIdMatch) {
      defaultColumn = sampleIdMatch;
    }
    setSelectedIdColumn(defaultColumn);
    setSearches(processSearchData(results.data, defaultColumn));

    // Report CSV formatting problems (e.g. ragged rows) without blocking the load.
    const problemRows = results.errors.length;
    const warning = problemRows > 0
      ? `"${fileName}" had ${problemRows} row(s) with formatting problems (for example a different ` +
        'number of columns than the header). Some values may not have loaded correctly.'
      : undefined;
    return { ok: true, warning };
  };

  /**
   * Load samples from a saved layout file. Unlike loadSampleCsvText, this sets the searches,
   * file name, columns, and ID column directly from the file's recorded settings, without
   * applying the auto-ID-column defaults. Bumps uploadCounter so the Sequence Export Wizard
   * remounts. The caller (App.applyLoadedLayout) restores the remaining settings.
   */
  const loadSearches = (
    loadedSearches: SearchData[],
    fileName: string,
    idColumn: string,
    metadataColumns: string[]
  ) => {
    setUploadCounter(c => c + 1);
    setSelectedFileName(fileName);
    setIsLayoutFile(true);
    setAvailableColumns([idColumn, ...metadataColumns]);
    setSelectedIdColumn(idColumn);
    setSearches(loadedSearches);
    // Imported layouts cannot be re-derived by changing the ID column, so clear parsedData.
    setParsedData([]);
  };

  /** Clear all file-derived state, returning the app to its pre-upload state. */
  const resetFileState = () => {
    setParsedData([]);
    setAvailableColumns([]);
    setSelectedIdColumn('');
    setSelectedFileName('');
    setSearches([]);
    setIsLayoutFile(false);
  };

  const handleIdColumnChange = (event: React.ChangeEvent<HTMLSelectElement>) => {
    const newIdColumn = event.target.value;
    setSelectedIdColumn(newIdColumn);

    if (parsedData.length > 0) {
      const processedSearches = processSearchData(parsedData, newIdColumn);
      setSearches(processedSearches);
    }
  };

  return {
    searches,
    parsedData,
    availableColumns,
    selectedIdColumn,
    selectedFileName,
    isLayoutFile,
    uploadCounter,
    loadSampleCsvText,
    handleIdColumnChange,
    loadSearches,
    resetFileState,
  };
}