import Papa from 'papaparse';
import {
  SearchData,
  RandomizationAlgorithm,
  GroupingConstraint,
  CovariateColorInfo,
} from './types';
import { buildPlacementCsv, getTextColorForBackground } from './utils';

/**
 * Save/load of a generated layout together with the settings that produced it.
 *
 * A layout file is a single CSV with two parts:
 *   1. A two-column "options" block: `key,value` rows (and `color:<covariateKey>` rows),
 *      led by a marker row `Octopus Layout,<schemaVersion>`. List values use `|`.
 *   2. The placement table: byte-for-byte the plain Download CSV (id column, metadata,
 *      plate, well).
 * The two parts are separated by a blank line, but parsing detects them by content (the
 * marker row, and the table header row that contains `plate` and `well`), so the file
 * survives an Excel round-trip that drops blank lines or pads rows with empty cells.
 *
 * Reproduction restores the recorded placement DIRECTLY (parse plate/well -> grid). It
 * never re-runs randomization, which uses unseeded Math.random and could not reproduce a
 * prior layout.
 */

export const LAYOUT_SCHEMA_VERSION = 1;
export const LAYOUT_MARKER = 'Octopus Layout';

/** The user-chosen configuration that produced a layout. */
export interface LayoutSettings {
  selectedIdColumn: string;
  selectedCovariates: string[];
  qcColumn: string;
  selectedQcValues: string[];
  selectedAlgorithm: RandomizationAlgorithm;
  keepEmptyInLastPlate: boolean;
  plateRows: number;
  plateColumns: number;
  subjectColumn: string;
  groupingConstraint: GroupingConstraint;
  /** Metadata column names in display order, so re-exports keep stable column order. */
  metadataColumns: string[];
}

export type CovariateColorMap = { [key: string]: CovariateColorInfo };

/** A single placement-table row, as parsed from the file. */
export interface LayoutRow {
  name: string;
  metadata: { [key: string]: string };
  plate: number;
  well: string;
}

export interface ParsedLayout {
  /** Settings from the options block, or null when the block is missing/incomplete. */
  settings: LayoutSettings | null;
  /** Colors from the `color:` rows, or null when none are present. */
  covariateColors: CovariateColorMap | null;
  /** Schema version declared in the marker row, or null when absent. */
  schemaVersion: number | null;
  /** True when the `Octopus Layout` options block was missing or could not be parsed. */
  headerMissing: boolean;
  rows: LayoutRow[];
}

export type LayoutValidationError =
  | { fatal: true; message: string }
  | { fatal: false; warning: string };

/**
 * PapaParse auto-generates field names for malformed columns ("_1", "__parsed_extra", or
 * blank). Mirrors the helper in useFileUpload so imported tables filter the same way.
 */
function isAutoGeneratedColumn(name: string): boolean {
  return /^_\d+$/.test(name.trim()) || name.trim() === '' || name === '__parsed_extra';
}

/** Split a `|`-joined list value, returning [] for an empty cell. */
function splitList(value: string): string[] {
  return value ? value.split('|') : [];
}

/** Encode a covariate color's fill style as a single token. */
function fillToken(info: CovariateColorInfo): string {
  if (info.useStripes) return 'stripes';
  if (info.useOutline) return 'outline';
  return 'solid';
}

/** Decode a fill token back into the outline/stripes flags. */
function fillFlags(token: string): { useOutline: boolean; useStripes: boolean } {
  return {
    useOutline: token === 'outline',
    useStripes: token === 'stripes',
  };
}

/** Convert a 1-based plate number to a 0-based plate index. */
export function plateToIndex(plate: number): number {
  return plate - 1;
}

/**
 * Convert a well label ("A01") to 0-based row/column indices. Inverse of getWell in utils.
 * @throws Error if the well is malformed or outside the plate bounds.
 */
export function wellToIndices(
  well: string,
  plateRows: number,
  plateColumns: number
): { row: number; col: number } {
  const match = /^([A-Za-z])(\d+)$/.exec(well.trim());
  if (!match) {
    throw new Error(`Malformed well "${well}" (expected a letter followed by digits, e.g. "A01")`);
  }
  const row = match[1].toUpperCase().charCodeAt(0) - 65; // A -> 0
  const col = parseInt(match[2], 10) - 1; // 01 -> 0
  if (row < 0 || row >= plateRows) {
    throw new Error(`Well "${well}" row is outside the plate (${plateRows} rows)`);
  }
  if (col < 0 || col >= plateColumns) {
    throw new Error(`Well "${well}" column is outside the plate (${plateColumns} columns)`);
  }
  return { row, col };
}

/**
 * Serialize a layout plus its settings and colors to the two-section CSV string.
 */
export function serializeLayout(options: {
  searches: SearchData[];
  randomizedPlates: (SearchData | undefined)[][][];
  settings: LayoutSettings;
  covariateColors: CovariateColorMap;
}): string {
  const { searches, randomizedPlates, settings, covariateColors } = options;

  const optionRows: string[][] = [
    [LAYOUT_MARKER, String(LAYOUT_SCHEMA_VERSION)],
    ['idColumn', settings.selectedIdColumn],
    ['covariates', settings.selectedCovariates.join('|')],
    ['qcColumn', settings.qcColumn],
    ['qcValues', settings.selectedQcValues.join('|')],
    ['algorithm', settings.selectedAlgorithm],
    ['keepEmptyInLastPlate', String(settings.keepEmptyInLastPlate)],
    ['plateRows', String(settings.plateRows)],
    ['plateColumns', String(settings.plateColumns)],
    ['subjectColumn', settings.subjectColumn],
    ['groupingConstraint', settings.groupingConstraint],
    ['metadataColumns', settings.metadataColumns.join('|')],
  ];
  Object.entries(covariateColors).forEach(([key, info]) => {
    optionRows.push([`color:${key}`, `${info.color} ${fillToken(info)}`]);
  });

  const optionsCsv = Papa.unparse(optionRows);
  const table = buildPlacementCsv(searches, randomizedPlates, settings.selectedIdColumn);
  return `${optionsCsv}\n\n${table}`;
}

/** Read cell at index, returning '' when absent. */
function cell(row: string[], index: number): string {
  const v = index >= 0 ? row[index] : undefined;
  return v === undefined || v === null ? '' : String(v);
}

/** True when a CSV line's comma-separated fields include both `plate` and `well`. */
function isTableHeaderLine(line: string): boolean {
  const cols = line.split(',').map((c) => c.trim());
  return cols.includes('plate') && cols.includes('well');
}

/**
 * Parse a two-section layout file into settings, colors, and placement rows. The file is
 * split into the options block and the placement table at the table-header line (the first
 * line whose columns include `plate` and `well`); the two parts are then parsed separately,
 * so blank-line and trailing-empty differences from an Excel round-trip do not matter.
 * When the options block is missing or incomplete, settings is null and headerMissing is
 * set, but the placement table is still parsed so the caller can degrade gracefully.
 */
export function parseLayout(fileText: string): ParsedLayout {
  const lines = fileText.split(/\r\n|\n|\r/);
  const headerIdx = lines.findIndex(isTableHeaderLine);

  const optionText = (headerIdx >= 0 ? lines.slice(0, headerIdx) : lines).join('\n');
  const tableText = headerIdx >= 0 ? lines.slice(headerIdx).join('\n') : '';

  // --- Options block ---
  const optionGrid = (
    Papa.parse<string[]>(optionText, { skipEmptyLines: 'greedy' }).data as string[][]
  ).filter(Array.isArray);

  const markerRow = optionGrid.find((row) => cell(row, 0) === LAYOUT_MARKER);
  const hasMarker = markerRow !== undefined;
  const schemaVersion = markerRow ? parseInt(cell(markerRow, 1), 10) : null;

  let settings: LayoutSettings | null = null;
  let covariateColors: CovariateColorMap | null = null;
  let headerMissing = !hasMarker;

  if (hasMarker) {
    const opt: { [key: string]: string } = {};
    const colors: CovariateColorMap = {};
    optionGrid.forEach((row) => {
      const key = cell(row, 0);
      const value = cell(row, 1);
      if (key === LAYOUT_MARKER) return;
      if (key.startsWith('color:')) {
        const covariateKey = key.slice('color:'.length);
        const [color, token] = value.split(/\s+/);
        colors[covariateKey] = {
          color,
          ...fillFlags(token),
          textColor: getTextColorForBackground(color),
        };
      } else if (key) {
        opt[key] = value;
      }
    });

    // Core settings must be present to reproduce the configuration.
    const hasCore = 'idColumn' in opt && 'plateRows' in opt && 'plateColumns' in opt;
    if (hasCore) {
      settings = {
        selectedIdColumn: opt['idColumn'],
        selectedCovariates: splitList(opt['covariates'] ?? ''),
        qcColumn: opt['qcColumn'] ?? '',
        selectedQcValues: splitList(opt['qcValues'] ?? ''),
        selectedAlgorithm: (opt['algorithm'] || 'balanced') as RandomizationAlgorithm,
        keepEmptyInLastPlate: opt['keepEmptyInLastPlate'] === 'true',
        plateRows: parseInt(opt['plateRows'], 10),
        plateColumns: parseInt(opt['plateColumns'], 10),
        subjectColumn: opt['subjectColumn'] ?? '',
        groupingConstraint: (opt['groupingConstraint'] || 'none') as GroupingConstraint,
        metadataColumns: splitList(opt['metadataColumns'] ?? ''),
      };
      covariateColors = Object.keys(colors).length > 0 ? colors : null;
    } else {
      headerMissing = true;
    }
  }

  // --- Placement table ---
  const rows: LayoutRow[] = [];
  if (headerIdx >= 0) {
    const table = Papa.parse<Record<string, string>>(tableText, {
      header: true,
      skipEmptyLines: true,
    });
    const idColumn = settings?.selectedIdColumn ?? (table.meta.fields?.[0] ?? '');
    table.data.forEach((row) => {
      if (!row || !row[idColumn]) return;
      const metadata: { [key: string]: string } = {};
      Object.keys(row).forEach((colName) => {
        if (colName === idColumn || colName === 'plate' || colName === 'well') return;
        if (isAutoGeneratedColumn(colName)) return;
        metadata[colName.trim()] = row[colName];
      });
      rows.push({
        name: row[idColumn],
        metadata,
        plate: parseInt(row['plate'], 10),
        well: (row['well'] ?? '').trim(),
      });
    });
  }

  return { settings, covariateColors, schemaVersion, headerMissing, rows };
}

/**
 * Rebuild the plates grid and plateAssignments map from parsed placement rows.
 * Metadata is rebuilt in the settings' metadataColumns order so re-exports stay stable.
 * Assumes the rows have already passed validateLayout.
 */
export function buildPlatesFromRows(
  rows: LayoutRow[],
  settings: LayoutSettings
): {
  plates: (SearchData | undefined)[][][];
  plateAssignments: Map<number, SearchData[]>;
  /** All placed samples in file-row order (same object references held by the plates). */
  samples: SearchData[];
} {
  const { plateRows, plateColumns, metadataColumns } = settings;
  const numPlates = rows.reduce((max, r) => Math.max(max, r.plate), 0);

  const plates: (SearchData | undefined)[][][] = Array.from({ length: numPlates }, () =>
    Array.from({ length: plateRows }, () =>
      Array.from({ length: plateColumns }, () => undefined as SearchData | undefined)
    )
  );
  const plateAssignments = new Map<number, SearchData[]>();
  const samples: SearchData[] = [];

  rows.forEach((row) => {
    // Rebuild metadata in the recorded column order.
    const metadata: { [key: string]: string } = {};
    metadataColumns.forEach((col) => {
      if (col in row.metadata) metadata[col] = row.metadata[col];
    });
    // Include any extra metadata columns not listed (defensive), preserving their values.
    Object.keys(row.metadata).forEach((col) => {
      if (!(col in metadata)) metadata[col] = row.metadata[col];
    });

    const sample: SearchData = { name: row.name, metadata };
    samples.push(sample);
    const plateIndex = plateToIndex(row.plate);
    const { row: r, col: c } = wellToIndices(row.well, plateRows, plateColumns);
    plates[plateIndex][r][c] = sample;

    const assigned = plateAssignments.get(plateIndex) ?? [];
    assigned.push(sample);
    plateAssignments.set(plateIndex, assigned);
  });

  return { plates, plateAssignments, samples };
}

/**
 * Validate a parsed layout before applying it. Returns all problems found; the caller
 * aborts on any { fatal: true }. A headerMissing layout is reported as a non-fatal warning.
 */
export function validateLayout(parsed: ParsedLayout): LayoutValidationError[] {
  const errors: LayoutValidationError[] = [];

  if (parsed.schemaVersion !== null && parsed.schemaVersion > LAYOUT_SCHEMA_VERSION) {
    errors.push({
      fatal: true,
      message:
        `This file was saved by a newer version of Octopus ` +
        `(schema version ${parsed.schemaVersion}). Please update to load it.`,
    });
    return errors;
  }

  if (parsed.headerMissing || !parsed.settings) {
    errors.push({
      fatal: false,
      warning:
        'This file has no Octopus settings; the plate layout was restored, ' +
        'but the saved options (covariates, colors, plate size) could not be applied.',
    });
    return errors;
  }

  const { plateRows, plateColumns } = parsed.settings;

  if (parsed.rows.length === 0) {
    errors.push({ fatal: true, message: 'The layout file contains no samples.' });
    return errors;
  }

  // Duplicate sample names.
  const seenNames = new Set<string>();
  const duplicateNames = new Set<string>();
  parsed.rows.forEach((row) => {
    if (seenNames.has(row.name)) duplicateNames.add(row.name);
    seenNames.add(row.name);
  });
  if (duplicateNames.size > 0) {
    errors.push({
      fatal: true,
      message: `Duplicate sample name(s) in the layout file: ${Array.from(duplicateNames).join(', ')}`,
    });
  }

  // Well/plate bounds and single occupancy.
  const occupied = new Set<string>();
  parsed.rows.forEach((row) => {
    if (!Number.isInteger(row.plate) || row.plate < 1) {
      errors.push({ fatal: true, message: `Sample "${row.name}" has an invalid plate "${row.plate}".` });
      return;
    }
    try {
      const { row: r, col: c } = wellToIndices(row.well, plateRows, plateColumns);
      const key = `${row.plate}:${r}:${c}`;
      if (occupied.has(key)) {
        errors.push({
          fatal: true,
          message: `Two samples occupy plate ${row.plate} well ${row.well}.`,
        });
      }
      occupied.add(key);
    } catch (e: any) {
      errors.push({ fatal: true, message: `Sample "${row.name}": ${e.message}` });
    }
  });

  return errors;
}
